spring.application.name=proyecto-veterinaria

# 1. Configuración de la base de datos MySQL
# IMPORTANTE: Cambia "root" y "tu_contraseña" por las credenciales reales de tu MySQL Workbench
spring.datasource.url=jdbc:mysql://localhost:3306/veterinaria_db?serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=lacancion0217
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Configuración de JPA / Hibernate
# 'update' creará las tablas automáticamente si no existen y las actualizará si hay cambios
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en consola (útil para ver qué hace JPA por detrás)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto específico para MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
